import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { numans, stackSansNotch } from "@/lib/font";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${numans.variable} ${numans.variable} antialiased ${numans.className} `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
